title: DIPPAM
email: hello@dippam.ac.uk
description: >
  DIPPAM is an online virtual archive of documents and sources relating to the history of Ireland, and its migration experience from the 18th to the late 20th centuries.
baseurl: ""
url: "http://www.dippam.ac.uk"
github_username:  dippam
markdown: kramdown
